name: locosopa
description: Low-code software homepages

inputs:
  config:
    description: Path to config file
    required: true
  path:
    description: Path to deploy to
    default: locosopa_action
outputs:
  page-url:
    description: page url
    value: ${{ steps.deployment.outputs.page_url }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: "koesterlab/locosopa"
        path: ${{ inputs.path }}
        ref: ${{ env.ACTION_REF }}

    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.11
        mamba-version: "*"
        channels: conda-forge,nodefaults
        activate-environment: test-env
        environment-file: ${{ inputs.path }}/locosopa/environment.yml

    - name: Build page
      shell: bash -el {0}
      run: |
        cd ${{ inputs.path }}/locosopa && snakemake -c1 --software-deployment-method conda --configfile ${{ inputs.config }}

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ${{ inputs.path }}/locosopa/build

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2

