name: test

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          config: .tests/config.yaml
          deploy: "false"
